### ISSUE TITLE
You can travel in pipes from cryo cells

### ISSUE THREAD

**Issue by Crystalwarrior** [AtlasStation/AtlasStation#19]
You can simply just walk down and you'll go into the cryo pipes. This is hilarious but also broken as you have to find another cryo cell to get out

**Comment by Crystalwarrior** [comment]
WOOP, YOU CAN ALSO TRAVEL IN PIPES WHEN BUCKLED TO THEM. GG.

**Comment by Chronitonity** [comment]
TG put up a fix for this, should be simple enuff to look through their prs

**Comment by Chronitonity** [comment]
fixed
