### ISSUE TITLE
LIZARDS CANT TALK

### ISSUE THREAD

**Issue by Foosili** [AtlasStation/AtlasStation#26]
Fucking liggers can't talk holy shit what

To reproduce: join server as ligger
try talk
??? nothing
set species human
can talk

?????????????????????????????????

**Comment by whitefox08** [comment]
Nex fucked some Datums in https://github.com/AtlasStation/AtlasStation/blob/beaca9f09c92f2c2c7b65546958ac803d6e8e3b9/code/modules/mob/living/carbon/human/species_types.dm

Fixed in 96b71a58c8
