### ISSUE TITLE
Scheduler vs Master Controller.

### ISSUE THREAD

**Issue by HoaxIT** [AtlasStation/AtlasStation#49]
So, the Master Controller is doing this.

```
				//AIR
				spawn(0)
					if(!air_processing_killed)
						timer = world.timeofday
						last_thing_processed = air_master.type
						air_master.process()
						air_cost = (world.timeofday - timer) / 10
						global_activeturfs = air_master.active_turfs.len`
```

and the Scheduler, is doing this.

```
/datum/controller/process/air/doWork()
	air_master.process_air()
```

Not sure, but why would you run both systems, at the same time, causing more CPU cycles, same goes for `nano` `gc` and other systems.

**Comment by Memendia** [comment]
http://cdn.funnyhub.com/2015/jan/facepalm/facepalm30.gif

**Comment by Crystalwarrior** [comment]
I'm not exactly sure but I think both serve a completely different function from each other.

**Comment by Memendia** [comment]
Ding Ding Ding Ding Ding!

We have a winner!!!

**Comment by HoaxIT** [comment]
`I'm not exactly sure but I think both serve a completely different function from each other.`
Not really, since the MC calls `air_master.process()` which does the following.

```
/datum/controller/air_system/proc/process()
	if(kill_air)
		return 1

	if(speed > 1)
		for(var/i=0,i<speed,i++)
			spawn((10/speed)*i)
				process_air()
	else
		process_air()
	return 1
```

the scheduler calls `process_air` directly, which does the following.

```
	current_cycle++
	var/timer = world.timeofday
	process_active_turfs()
	master_controller.air_turfs = (world.timeofday - timer) / 10

	timer = world.timeofday
	process_excited_groups()
	master_controller.air_groups = (world.timeofday - timer) / 10

	timer = world.timeofday
	process_high_pressure_delta()
	master_controller.air_highpressure = (world.timeofday - timer) / 10

	timer = world.timeofday
	process_hotspots()
	master_controller.air_hotspots = (world.timeofday - timer) / 10

	timer = world.timeofday
	process_super_conductivity()
	master_controller.air_superconductivity = (world.timeofday - timer) / 10
```
so, essentially, you're doing the same, in two seperate systems.

**Comment by Crystalwarrior** [comment]
Oh, welp. I see what you mean now.

**Comment by HoaxIT** [comment]
Besides that, having the `MasterController` while running an `Scheduler` is like driving an car, and an bike at the same time, it both works, but the one goes faster than another, i suggest moving all `MasterController` logics/loops into `Scheduler` tasks, and moving some things inside `world.dm` and `master_controller.dm` into `/datum/controller/process/ticker/setup()` or proper `Scheduler` processes.

**Comment by HoaxIT** [comment]
Pinging @JamieH since he initially wrote this.

**Comment by JamieH** [comment]
Afraid I'm away for next couple of days, shall have a look when I get back

**Comment by JamieH** [comment]
Not an issue. The old MasterController never has .process called on it so it never starts processing, mainly just left the code there for legacy purposes.
