### ISSUE TITLE
RBG Selection window for palette doesn't remember what color was selected.

### ISSUE THREAD

**Issue by whitefox08** [AtlasStation/AtlasStation#73]
https://dl.dropboxusercontent.com/u/20521740/ShareX/2015/06/2015-06-03_17-02-27.mp4

**Comment by Crystalwarrior** [comment]
Unless BYOND lets you set the color input settings on the whim I can't do anything about it.
Also it's RGB you CUCK.

**Comment by whitefox08** [comment]
:^)
