### ISSUE TITLE
Feature Request: Pixel Projectile Dynamic Range

### ISSUE THREAD

**Issue by Fox-McCloud** [AtlasStation/AtlasStation#76]
Currently pixel projectiles are based around a hardcoded value of 480.

Request: Have this dynamically assigned based on the client's current view size.

Why?

- Adminbus gun shenanigans at long range
- Some guns have a scope on them that alters view range if you stand still and zoom in with it...but this instantly means that the value of 480 will result in wildly inaccurate shots.

**Comment by Crystalwarrior** [comment]
But... the pixel projectiles already support dynamic range.
'''
			//Calculate the "resolution" of screen based on client's view and world's icon size. This will work if the user can view more tiles than average.
			var/screenview = (user.client.view * 2 + 1) * world.icon_size //Refer to http://www.byond.com/docs/ref/info.html#/client/var/view for mad maths
'''

**Comment by Fox-McCloud** [comment]
Wasn't aware you added support for that. My mistake!
